# Generated by Django 4.2.7 on 2023-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_rename_ldate_applyscheme_lastdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('season', models.TextField()),
                ('soildetails', models.TextField()),
                ('pesticides', models.DateField()),
            ],
        ),
    ]
