# Generated by Django 4.2.7 on 2023-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_alter_addcrops_pesticides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('applicant_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='aadhar_cards/')),
                ('ration_card', models.ImageField(blank=True, null=True, upload_to='ration_cards/')),
            ],
        ),
    ]
