# Generated by Django 4.2.7 on 2023-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0005_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_name',
            new_name='Applicant_Name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='scheme_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
